### ISSUE TITLE
Edit portfolio-details.html

### ISSUE THREAD

**Issue by rahulaarora** [kambojshalabh35/cakhseft-development#11]
![image](https://user-images.githubusercontent.com/24794534/193399573-399cab3b-7978-4e85-a0fc-a7a8d1880b65.png)
I can edit the brand name and improve this template @kambojshalabh35

**Comment by rahulaarora** [comment]
Hi @kambojshalabh35 , could you assign this issue to me?

**Comment by kambojshalabh35** [comment]
@rahulaarora you may start working on the issue
