### ISSUE TITLE
Edit portfolio-detail page

### ISSUE THREAD

**Issue by kambojshalabh35** [kambojshalabh35/cakhseft-development#27]
Remove all the unnecessary details, just leave the image slider,  name and description to it, in description add lorem for the time.

**Comment by rahulaarora** [comment]
could you assign this to me ? @kambojshalabh35

**Comment by kambojshalabh35** [comment]
@rahulaarora you may start working on the issue

**Comment by rahulaarora** [comment]
@kambojshalabh35

**Comment by rahulaarora** [comment]
I made the changes
