### ISSUE TITLE
Create index.html using bootstrap 5

### ISSUE THREAD

**Issue by kambojshalabh35** [kambojshalabh35/cakhseft-development#6]
Add a file index.html with the help of bootstrap 5 in that add navigation bar and implement custom css and js to it.

**Comment by Arun23397** [comment]
Can you please assign this project to me

**Comment by kambojshalabh35** [comment]
@Arun23397 you have been assigned the project work; please begin working on it.

**Comment by jmtherapy** [comment]
May I work on this

**Comment by Arun23397** [comment]
Hii @kambojshalabh35 which navigation you want top, bottom or side??

**Comment by kambojshalabh35** [comment]
Top navigation and kindly add the logo to it which is placed at Assets/img/logo.png

**Comment by kambojshalabh35** [comment]
@Arun23397 can you please move all the scripts used in the HTML code just above the </body> tag and remove unwanted comments.

**Comment by Arun23397** [comment]
yeah done
