### ISSUE TITLE
Edit the portfolio section.

### ISSUE THREAD

**Issue by kambojshalabh35** [kambojshalabh35/cakhseft-development#9]
add the portfolio items from: https://shalabhkamboj.vercel.app
just add the names and in place of the photo add the logo of the company.

**Comment by Milind-Palaria** [comment]
hey @kambojshalabh35  i would like to contribute to this, can u assign this work to me?

**Comment by kambojshalabh35** [comment]
@Milind-Palaria you may start working on the issue

**Comment by kambojshalabh35** [comment]
@Milind-Palaria the site started breaking kindly resolve the issue as soon as possible

**Comment by Milind-Palaria** [comment]
@kambojshalabh35 kindly specify the problems, so i can work on them.

**Comment by kambojshalabh35** [comment]
the company logos overflowing and going in the faq page and too the size of the logos is large

**Comment by Milind-Palaria** [comment]
ok i will fix these issues.
